### ISSUE TITLE
Decoding Interactive Demo Error 

### ISSUE THREAD

**Issue by dangolbeeker** [paulmillr/qr#3]
[ERROR] Media loop [object OverconstrainedError]

Chrome Version: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99

**Comment by paulmillr** [comment]
Will check it out.

**Comment by dangolbeeker** [comment]
Ok Cool

**Comment by paulmillr** [comment]
fixed, but will fix more

**Comment by dangolbeeker** [comment]
Awesome
