### ISSUE TITLE
Kotlin/JS usage in Readme

### ISSUE THREAD

**Issue by Queatz** [paulmillr/qr#7]
Spent a bit of time trying to figure out the right way to import into a Kotlin/JS project. This is what it needed to be, might be helpful to have a blurb in the readme:

```kotlin
@JsModule("@paulmillr/qr")
@JsNonModule
external object Qr {
    @JsName("default")
    fun createQR(text: String, output: String = definedExternally, opts: dynamic = definedExternally): Uint8Array
}
```

Then it can be used like:

```kotlin
val bytes = Qr.createQR("text", "gif", js("{ scale: 10 }"))
val blob = Blob(arrayOf(bytes), BlobPropertyBag("image/gif"))
val imgSrc = URL.createObjectURL(blob)
```

Note, this is only neccessary to do manually until the Dukat project rewrite is finished by the Kotlin team.

**Comment by paulmillr** [comment]
added
